version: 2.1
jobs:

  #------------------------------------------------------------
  # 1. 安装依赖
  #------------------------------------------------------------
  install-dependencies:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps

      - run:
          name: 'Install dependencies'
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  #------------------------------------------------------------
  # 2. 构建
  #------------------------------------------------------------
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - attach_workspace:
          at: ~/project
      
      - run:
          name: 'Run build'
          command: yarn build
      
      - persist_to_workspace:
          root: ~/project
          paths:
            - .vuepress/dist
  
  #------------------------------------------------------------
  # 3. 部署
  #------------------------------------------------------------
  deploy:
    docker:
      - image: instrumentisto/rsync-ssh:latest
    steps:
      - attach_workspace:
          at: ~/project

      - add_ssh_keys:
          fingerprints:
            - "43:b9:67:4e:7c:08:eb:89:55:96:e6:f9:82:cd:c8:d1"
      
      - run:
          name: Deploy Over Rsync
          command: |
            rsync -az --progress --delete-after -e "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" .vuepress/dist/ $SSH_DEPLOY_USER@$SSH_HOST:/etc/nginx/html
workflows:
  build:
    jobs:
      - install-dependencies
      - build:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
          